replicaCount: 1

image:
  repository: containers.renci.org/neurobridges/backend-service
  tag: "1.1.0"

# Use port specified by the webapp container here
# the external ingress will always use the https port (443/tcp)
service:
  type: ClusterIP
  port: 8080

resources:
  limits:
    cpu: 250m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

ingress:
  host: neurobridge-api.apps.renci.org
